version: "3.9"
services:
  VulnerableApp-base:
    build: ./base
    image: vulnerableapp-base:local

  VulnerableApp-jsp:
    build: ./jsp
    image: vulnerableapp-jsp:local

  VulnerableApp-php:
    build: ./php
    image: vulnerableapp-php:local

  VulnerableApp-facade:
    build: ./facade
    depends_on:
      - VulnerableApp-base
      - VulnerableApp-jsp
      - VulnerableApp-php
    image: vulnerableapp-facade:local
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
